#!/bin/bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
"$ROOT/scripts/make-app.sh"
STAGE="$(mktemp -d /tmp/envstudio-dmg.XXXXXX)"
DMG="$ROOT/dist/EnvStudio-arm64.dmg"
ditto "$ROOT/dist/EnvStudio.app" "$STAGE/EnvStudio.app"
xattr -cr "$STAGE/EnvStudio.app"
codesign --force --sign - "$STAGE/EnvStudio.app"
codesign --verify --deep --strict "$STAGE/EnvStudio.app"
ln -s /Applications "$STAGE/Applications"
rm -f "$DMG"
hdiutil create -volname "Env Studio" -srcfolder "$STAGE" -ov -format UDZO "$DMG"
rm -rf "$STAGE"
echo "DMG: $DMG"
